from __future__ import annotations

from pathlib import Path
from types import MethodType

from PySide6.QtWidgets import QApplication, QFileDialog, QMessageBox, QProgressDialog

from pdf_workbench.core.ocr_bundle import export_ocr_bundle
from pdf_workbench.gui.workspace_resume import _write_workspace


def install_bundle_update(window) -> None:
    """Let Export for OCR update an existing bundle safely.

    The core exporter writes a complete replacement into a temporary directory
    first, then swaps it into place. Files not generated by PDF Workbench are
    carried forward, so OCR results or notes saved inside the bundle survive.
    """

    # The application workflow is OCR-bundle centric. Keep the older plain PDF
    # export implementation available internally, but remove it from the UI.
    if hasattr(window, "export_button"):
        window.export_button.setVisible(False)
        window.export_button.setEnabled(False)

    def export_for_ocr_with_update(self) -> None:
        if self.pdf_path is None or self.doc is None:
            return

        parent = QFileDialog.getExistingDirectory(
            self,
            "Choose folder for OCR bundle",
            str(self.pdf_path.parent),
        )
        if not parent:
            return

        bundle_dir = Path(parent) / f"{self.pdf_path.stem}_ocr_bundle"
        replace_existing = bundle_dir.is_dir() and any(bundle_dir.iterdir())

        if replace_existing:
            answer = QMessageBox.question(
                self,
                "既存OCR Bundleを更新",
                f"同名のOCR Bundleがすでにあります。\n\n{bundle_dir}\n\n"
                "現在の分割設定・manifest.json・workspace.json・OCR用分割PDFを更新します。\n"
                "PDF Workbenchが生成したものではない追加ファイル（OCR済みPDFなど）は保持します。\n\n"
                "このBundleを更新しますか？",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.Yes,
            )
            if answer != QMessageBox.StandardButton.Yes:
                return

        progress = QProgressDialog(
            "Updating OCR bundle…" if replace_existing else "Creating OCR bundle…",
            "Cancel",
            0,
            len(self.doc),
            self,
        )
        progress.setWindowTitle("PDF Workbench")
        progress.setMinimumDuration(0)

        def on_progress(done: int, total: int) -> bool:
            progress.setMaximum(total)
            progress.setValue(done)
            QApplication.processEvents()
            return not progress.wasCanceled()

        try:
            result = export_ocr_bundle(
                self.pdf_path,
                bundle_dir,
                self.page_settings,
                dpi=self.dpi_spin.value(),
                quality=self.quality_spin.value(),
                grayscale=self.grayscale.isChecked(),
                include_original=self.include_original.isChecked(),
                replace_existing=replace_existing,
                progress=on_progress,
            )
            _write_workspace(self, result.bundle_dir)
            progress.close()
            title = "OCR bundle updated" if replace_existing else "OCR bundle complete"
            action = "更新しました" if replace_existing else "作成しました"
            QMessageBox.information(
                self,
                title,
                f"OCR Bundleを{action}。\n\n"
                f"Source pages: {result.source_page_count}\n"
                f"Split pages: {result.output_page_count}\n"
                f"作業再開情報: workspace.json\n\n"
                f"{result.bundle_dir}",
            )
        except InterruptedError:
            progress.close()
            self.statusBar().showMessage("OCR bundle export cancelled（既存Bundleは変更していません）")
        except Exception as exc:
            progress.close()
            QMessageBox.critical(self, "OCR bundle export failed", str(exc))

    try:
        window.export_ocr_button.clicked.disconnect()
    except (RuntimeError, TypeError):
        pass
    window.export_for_ocr = MethodType(export_for_ocr_with_update, window)
    window.export_ocr_button.clicked.connect(window.export_for_ocr)
